[tools]
zig = "0.15.2"

[vars]
sdcard_path = "/Volumes/NO NAME/pico2-apps"

[tasks.clean]
run = "rm -rf {{config_root}}/zig-out"

[tasks.build]
run = "zig build"

[tasks.test]
run = "zig build test"

[tasks.burn]
confirm  = "Insert SD Card"
depends  = ["build"]
run = """
cp {{config_root}}/zig-out/firmware/blinky.uf2 "{{vars.sdcard_path}}"
cp {{config_root}}/zig-out/firmware/synth.uf2 "{{vars.sdcard_path}}"
ls -la "{{vars.sdcard_path}}"
diskutil umount "/Volumes/NO NAME"
"""

[tasks.go]
description = "Build and run the mac native binary"
depends = [ "test", "build"]
run = [
    "{{config_root}}/zig-out/bin/synth-native"
]
