[tools]
zig = "0.15.2"


[tasks.build]
run = "zig build"

[tasks.burn]
confirm  = "Insert SD Card"
depends  = ["build"]
run = """
cp {{config_root}}/zig-out/firmware/blinky.uf2 "/Volumes/NO NAME/pico2-apps"
cp {{config_root}}/zig-out/firmware/synth.uf2 "/Volumes/NO NAME/pico2-apps"
diskutil umount "/Volumes/NO NAME"
"""
